llm:
  provider: ollama
  config:
    model: 'llama2'
    temperature: 0.5
    top_p: 1
    stream: true
    base_url: 'https://55.55.55.55:8080'

embedder:
  provider: ollama
  config:
    model: 'nomic-embed-text'
    base_url: 'https://55.55.55.55:8080'
